#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

rm -rf log.*

rm -rf 1 2 constant/polyMesh 

rm -rf geom_files.txt
#------------------------------------------------------------------------------
